[changelog]
header = """# Changelog

All notable changes to this project are documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
This project follows a pre-production workflow until the first production deployment.

---

"""

body = """
{% if version %}\
## [{{ version }}]
{% else %}\
## [Unreleased]

{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}\
- {% if commit.scope %}**{{ commit.scope }}**: {% endif %}{{ commit.message }}
{% endfor %}
{% endfor %}
---
"""

footer = ""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false

commit_parsers = [
  { message = "\\[skip ci\\]", skip = true },
  { message = "^Merge", group = "Integration" },
  { message = "^feat", group = "Added" },
  { message = "^fix", group = "Fixed" },
  { message = "^remove", group = "Removed" },
  { message = "^refactor", group = "Changed" },
  { message = "^style", group = "Changed" },
  { message = "^perf", group = "Changed" },
  { message = "^chore", group = "Changed" },
  { message = "^docs", group = "Changed" },
  { message = "^test", group = "Changed" },
  { message = "^build", group = "Changed" },
  { message = "^ci", group = "Changed" },
  { message = "^revert", group = "Fixed" },
  { message = ".*", group = "Changed" },
]

filter_commits = false
topo_order = false
sort_commits = "newest"
